name: 24-7 News Cloud Automator

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

env:
  # This fixes the June 2026 GitHub warning perfectly
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Copy project files to cloud server
        uses: actions/checkout@v4

      - name: Run your news parser code
        run: node index.js

      - name: Read text content
        id: read_content
        run: |
          echo "SUBJECT=$(cat email_subject.txt)" >> $GITHUB_ENV
          
      - name: Send Post to Blogger via Email Robot
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MY_EMAIL}}
          password: ${{secrets.MY_EMAIL_APP_PASSWORD}}
          subject: "${{ env.SUBJECT }}"
          to: authenticnews@blogger.com
          from: Cloud Scraper Robot
          body: file://email_body.txt # Changed 'box' to 'body' here!
