name: 24-7 Direct News Automator

on:
  schedule:
    - cron: '0 * * * *' # Automatically runs every hour
  workflow_dispatch: # Allows you to click the manual test button

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Copy project files
        uses: actions/checkout@v4

      - name: Run code to scrape and upload news
        run: node index.js
